### PR TITLE
added loglevel

### PR DESCRIPTION
**Pull request by derBobo**
added the possibility to filter the Log output by Log Category

### CODE REVIEW

**Comment by xPaw** [comment]
While I can see the usefulness of doing this, it's not necessary for SteamDB itself, as all the logs are relevant.

From the readme: "This source code is provided as-is for reference. It is highly tuned for SteamDB's direct needs and is not a generic application."

**Comment by derBobo** [comment]
You're right it's not necessary for the steamdb production server but, I noticed it sometimes is quite usefull to disable all the debug and info lines for development .
so i would say it's a feature for the steamdb devs not the steamdb production server.

**Comment by xPaw** [comment]
> so i would say it's a feature for the steamdb devs not the steamdb production server.

I'm the only dev, and these logs are useful when developing too.

**Comment by derBobo** [comment]
> these logs are useful when developing too.
thats why i said its sometimes usefull.

I think I'll close my pull request then.

BTW. impressive work

**Comment by xPaw** [comment]
Thanks for the PR, hopefully it is understandable that I'm keeping the code strictly tuned for SteamDB's needs.

**Pull request closed without merging**
